export const homeImages = [
  {
    id: 1,
    src: "/storm.png",
    title: "FIL STORM ",
    link: "/products?categories=Power+Bank",
    desc: "Lorem ipsum dolor sit amet consectetur. Dui mauris libero nulla congue enim duis phasellus congue. Lorem purus consectetur vel varius malesuada ullamcorper non scelerisque vitae.",
    titleStyle: "",
    descStyle: "",
  },
  {
    id: 2,
    src: "/fans.png",
    title: "FIL FANS",
    link: " /products?categories=Lifestyle",
    desc: "Lorem ipsum dolor sit amet consectetur. Dui mauris libero nulla congue enim duis phasellus congue. Lorem purus consectetur vel varius malesuada ullamcorper non scelerisque vitae.",
    titleStyle: "",
    descStyle: "",
  },
  {
    id: 3,
    src: "/extension.png",
    title: "FIL EXTENSIONS",
    link: "/products?categories=Extensions",
    desc: "Lorem ipsum dolor sit amet consectetur. Dui mauris libero nulla congue enim duis phasellus congue. Lorem purus consectetur vel varius malesuada ullamcorper non scelerisque vitae.",
    titleStyle: "",
    descStyle: "",
  },
  {
    id: 4,
    src: "/hero1.png",
    title: "POWER BANK",
    link: "/products?categories=Power+Bank",
    desc: "Lorem ipsum dolor sit amet consectetur. Dui mauris libero nulla congue enim duis phasellus congue. Lorem purus consectetur vel varius malesuada ullamcorper non scelerisque vitae.",
    titleStyle: "",
    descStyle: "",
  },
  {
    id: 5,
    src: "/filpods.png",
    title: "FIL EARBUDS",
    link: "/products?categories=Wearables",
    desc: "Lorem ipsum dolor sit amet consectetur. Dui mauris libero nulla congue enim duis phasellus congue. Lorem purus consectetur vel varius malesuada ullamcorper non scelerisque vitae.",
    titleStyle: "",
    descStyle: "",
  },
];
